# Generated by Django 2.0.3 on 2018-04-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryQueryResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.NullBooleanField(default=False, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_synchronize', '未同步'), ('synchronized', '已同步'), ('refused', '拒绝')], default='未同步', max_length=30, verbose_name='库存同步状态')),
                ('owner_code', models.CharField(max_length=20, verbose_name='货主编码')),
                ('warehouse_code', models.CharField(max_length=40, verbose_name='仓库编码')),
                ('warehouse_id', models.CharField(max_length=20, null=True, verbose_name='仓库id')),
                ('warehouse_name', models.CharField(max_length=32, null=True, verbose_name='仓库名称')),
                ('inventory_type', models.CharField(choices=[('ZP', '正品'), ('CC', '残次'), ('JS', '机损'), ('XS', '箱损'), ('ZT', '在途库存')], max_length=10, verbose_name='库存类型')),
                ('wms_quantity', models.IntegerField(verbose_name='wms系统商品总量')),
                ('wms_lock_quantity', models.IntegerField(verbose_name='wms系统锁定商品量')),
                ('oms_quantity', models.IntegerField(verbose_name='oms系统商品总量')),
                ('oms_lock_quantity', models.IntegerField(verbose_name='wms系统锁定商品量')),
                ('quantity_diff', models.IntegerField(default=0, verbose_name='总库存差值')),
                ('lock_quantity_diff', models.IntegerField(default=0, verbose_name='锁定库存差值')),
                ('item_id', models.CharField(max_length=40, null=True, verbose_name='仓储系统商品ID')),
                ('item_code', models.CharField(max_length=30, null=True, verbose_name='商家编码')),
                ('batch_code', models.CharField(max_length=30, null=True, verbose_name='批次编码')),
                ('product_date', models.DateTimeField(null=True, verbose_name='商品生产日期(YYYY-MM-DD)')),
                ('expire_date', models.DateTimeField(null=True, verbose_name='商品过期日期(YYYY-MM-DD)')),
                ('produce_code', models.CharField(max_length=30, null=True, verbose_name='生产批号')),
                ('sync_comments', models.CharField(default='', max_length=100, verbose_name='同步备注')),
                ('operator_id', models.CharField(max_length=30, null=True, verbose_name='操作员id')),
            ],
            options={
                'db_table': 'inventory_query_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkuCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.NullBooleanField(default=False, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20, verbose_name='目录名称')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('super_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='dbtest.SkuCategory')),
            ],
            options={
                'db_table': 'oms_sku_category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('user_id', 'item_code')},
        ),
        migrations.AlterModelTable(
            name='sku',
            table='sku',
        ),
        migrations.AddField(
            model_name='sku',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbtest.SkuCategory', verbose_name='产品类别'),
        ),
    ]
