# Generated by Django 2.0.3 on 2018-04-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0002_auto_20180403_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuItemId',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.NullBooleanField(default=False, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_id', models.CharField(max_length=20, verbose_name='同步的仓库')),
                ('user_id', models.CharField(max_length=20, verbose_name='货主编码即用户id')),
                ('item_code', models.CharField(max_length=64, verbose_name='商家编码')),
                ('item_id', models.CharField(max_length=64, verbose_name='仓库商品编码')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Sku', verbose_name='关联的商品')),
            ],
            options={
                'db_table': 'sku_item_id',
            },
        ),
        migrations.AlterUniqueTogether(
            name='skuitemid',
            unique_together={('sku', 'warehouse_id')},
        ),
    ]
