# Generated by Django 2.0.3 on 2018-04-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0003_auto_20180403_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuWarehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.NullBooleanField(default=False, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='Sku库存总数量')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='可用Sku库存数量')),
                ('gross_weight', models.IntegerField(default=0, verbose_name='毛重，单位克')),
                ('net_weight', models.IntegerField(default=0, verbose_name='净重，单位克')),
                ('length', models.IntegerField(default=0, verbose_name='单位毫米')),
                ('width', models.IntegerField(default=0, verbose_name='单位毫米')),
                ('height', models.IntegerField(default=0, verbose_name='单位毫米')),
                ('volume', models.IntegerField(default=0, verbose_name='单位立方厘米')),
                ('warehouse_id', models.CharField(max_length=20, verbose_name='仓库id')),
                ('warehouse_name', models.CharField(max_length=32, verbose_name='仓库名称')),
                ('warehouse_province', models.CharField(max_length=32, null=True, verbose_name='仓库省份')),
                ('warehouse_city', models.CharField(max_length=32, null=True, verbose_name='仓库城市')),
                ('warehouse_area', models.CharField(max_length=32, null=True, verbose_name='仓库地区')),
                ('warehouse_detail', models.CharField(max_length=32, null=True, verbose_name='仓库详细地址')),
                ('warehouse_longitude', models.CharField(max_length=32, null=True, verbose_name='仓库经度')),
                ('warehouse_latitude', models.CharField(max_length=32, null=True, verbose_name='仓库纬度')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Sku', verbose_name='Sku')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
